### ISSUE TITLE
Возможность конфигурирования GridView из модели

### ISSUE THREAD

**Issue by s1lver** [cusodede/yii2-default-controller#13]
Сейчас конфигурация, по умолчанию, происходит вызовом `array_keys($model->attributes)`. Чтобы переопределить набор или порядок следования колонок приходится, дополнительно, тащить похожую вьюху. Это не совсем удобно.

Предлагаю добавить возможность такой конфигурации. Например, в модель добавляем метод `public function getGridViewColumn():array` а во вьюхе добавляем условие `$model->gridViewColumn??array_keys($model->attributes)`

Это позволит избавится от копипаста файлов и конфигурировать все напрямую из модели.

**Comment by pozitronik** [comment]
Мысль понятна, но перегружать модель методом конфигурирования колонок... ну как-то это неправильно, в идеале конфиг должен быть в каком-то конфиге.
Что если я добавлю возможность задавать такой конфиг через `Yii::$app->components->default_controller->models->{Model::class}->gridColumns`?

**Comment by s1lver** [comment]
> Мысль понятна, но перегружать модель методом конфигурирования колонок... ну как-то это неправильно, в идеале конфиг должен быть в каком-то конфиге. Что если я добавлю возможность задавать такой конфиг через `Yii::$app->components->default_controller->models->{Model::class}->gridColumns`?

Думаю так потеряем в гибкости. Да и хранить настройки колонок в отдельном конфиге мне не нравится.
Тут основная мысль - избавится от ненужных копипастов при необходимости минимальных доработок. А так выходит что текущий вариант не удобен, что конфигурирование в конфиге не удобно.

**Comment by s1lver** [comment]
ps.. про перегрузку моделей. у нас полно пустых моделей, это им точно пойдет на пользу
