### ISSUE TITLE
Исправить определение $redirectAction после редактирования

### ISSUE THREAD

**Issue by eoskin-ru** [cusodede/yii2-default-controller#23]
В строке

> https://github.com/cusodede/yii2-default-controller/blob/13a7e3049f54470d48973a81f0c8178677140e76/src/models/DefaultController.php#L327C50-L327C70

заменить на `static::getAfterUpdateAction()`.

**Comment by pozitronik** [comment]
Нужно разобраться с упавшим CI

**Comment by pozitronik** [comment]
Fixed #25
