### ISSUE TITLE
Изменить значение по умолчанию для $enablePrototypeMenu

### ISSUE THREAD

**Issue by s1lver** [cusodede/yii2-default-controller#5]
Предлагаю поменять значение по умолчанию для `$enablePrototypeMenu`. Это какое-то очень редкое свойство которое приходится переопределять в каждом контроллере. 

Сейчас 
```php
/**
* @var bool $enablePrototypeMenu
*/
public bool $enablePrototypeMenu = true;
```

поменять на 
```php
/**
* @var bool $enablePrototypeMenu
*/
public bool $enablePrototypeMenu = false;
```

Конечно придется, при обновлении, убрать переопределение везде. Но, это лучше чем продолжать заниматься переопределением.

**Comment by pozitronik** [comment]
Я вообще хочу эту хрень с генератором меню убрать, она перестала использоваться после окончания прототипирования.

**Comment by pozitronik** [comment]
Начиная с 1.0.8 свойство `$enablePrototypeMenu` по умолчанию равно `false` и объявлено устаревшим. Метод генерации пунктов меню также объявлен устаревшим.
Этот код позже выпилю, он был актуален, когда компонент служил для быстрого прототипирования.
